### ISSUE TITLE
[REQ] Steam Group Check

### ISSUE THREAD

**Issue by danir-de** [KitsuneLab-Development/CS2-SteamRestrict#11]
Add a check for users being a member of a given Steam group. 
This way it's possible to ensure users are part of a community.

Since Steam groups can also private/invite-only, this would also be an additional way to create an easy to maintain server whitelist.

**Comment by K4ryuu** [comment]
Greetings,
The feature will be added shortly. 
Thank you.

**Comment by K4ryuu** [comment]
The feature has been added to pre-release.
