### ISSUE TITLE
[REQ] Cache/storage system for players' Steam profiles

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#12]
Database to save players' Steam profiles, so that after passing verification they can put their private Steam profile back.

With the option to configure it to automatically delete after X days.

And updating the database data every X days and if the profile is private, it leaves the old data until the date of automatic deletion of their records.

And with automatic updating so to speak, in case the player takes BAN VAC, GameBans and/or TradeBans, register it in the database and block the player's connection if the options `Block Trade Banned`, `Block VAC Banned` and `Block Game Banned` are active in the plugin.

**Comment by NaathySz** [comment]
![image](https://github.com/KitsuneLab-Development/CS2-SteamRestrict/assets/97997774/1340466c-37b4-4e6f-b9e1-c90a249b0b8e)

**Comment by K4ryuu** [comment]
The feature has been implemented to the upcoming release.
