### ISSUE TITLE
[REQ] kick info in player console

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#13]
CSGO and CS 1.6 some plugins when kicking the player informed the reason for the kick and in the console more information about the kick.

![image](https://github.com/KitsuneLab-Development/CS2-SteamRestrict/assets/32937653/fd20654a-6550-4204-9291-19a1181851ce)

Would something like this be possible for Steam Restrict kick reasons?

As CS2 does not allow modifying the reason for the kick, I believe that nothing can be done on the console, inform the player's console of the reason for the kick in more detail, reason for Private Profile, VAC Ban, Game Bans and others.

**Comment by K4ryuu** [comment]
Greetings,
I have tested this and it's not possible sadly. I tried to move to other event which is later on, also I tried to delay with seconds, but the message cannot be shown yet to player console. If I delay more the player can select teams. :/

**Comment by K4ryuu** [comment]
![CleanShot 2024-05-21 at 23 08 14@2x](https://github.com/KitsuneLab-Development/CS2-SteamRestrict/assets/104531589/87d30086-f831-478c-89e1-e3a37ed852d6)
This structure I made to list all violations :/ It was so cool, but can't be seen.
