### ISSUE TITLE
[BUG] plugin fails to calculate properly based on given config

### ISSUE THREAD

**Issue by lostsoul6** [KitsuneLab-Development/CS2-SteamRestrict#14]
@K4ryuu Hi there ,

I saw a rage hacker in server . checked his account and it was created 3 days ago . I have set plugin to not let accounts with less than 15 days age enter the server but he was in the server destroying everyone 😄 checked console logs and api has detected his account creation day correctly . it seems to me that the checks are failing . plugin isn't interpreting data correctly .

![dontwork](https://github.com/KitsuneLab-Development/CS2-SteamRestrict/assets/127633547/85a2dde3-a12c-47b1-8943-c4544fce4663)

hacker profile : https://steamid.io/lookup/76561199689872203

here is the config file : 

```
// This configuration was automatically generated by CounterStrikeSharp for plugin 'KitsuneSteamRestrict', at 2024/05/20 12:36:31
{
  "SteamWebAPI": "A0032C0DA4B6E67676767676",
  "MinimumCS2LevelPrime": -1,
  "MinimumCS2LevelNonPrime": -1,
  "MinimumHourPrime": 48,
  "MinimumHourNonPrime": 48,
  "MinimumLevelPrime": -1,
  "MinimumLevelNonPrime": -1,
  "MinimumSteamAccountAgeInDays": 15,
  "BlockPrivateProfile": false,
  "BlockTradeBanned": false,
  "BlockVACBanned": true,
  "SteamGroupID": "",
  "BlockGameBanned": false,
  "DatabaseSettings": {
    "host": "localhost",
    "username": "cs2767667766767",
    "database": "cs27667676767",
    "password": "0Kqq6766777676",
    "port": 3306,
    "sslmode": "none",
    "table-prefix": "",
    "table-purge-days": 365
  },
  "ConfigVersion": 2
}
```

I would be really thankful if you could fix this . this plugin is very needed for my server. thank you.

**Comment by K4ryuu** [comment]
I have checked and refactored the code. Sadly I checked only after the refactor and it works well. I'm uploading that patch now.
