### ISSUE TITLE
[REQ] SPAM WARNING TO PLAYER

### ISSUE THREAD

**Issue by ghostt187** [KitsuneLab-Development/CS2-SteamRestrict#16]
Would it be good if a player with private account joins and the plugin spams a message to him in chat x times like PLAYER MAKE YOUR ACCOUNT PUBLIC OR U WILL BE KICKED if he doesnt the plugin kicks him

**Comment by K4ryuu** [comment]
I recommend you reading https://github.com/KitsuneLab-Development/CS2-SteamRestrict/issues/13

Not planned to let the player join.

**Comment by K4ryuu** [comment]
The feature has been added to the latest upcoming release as bounty was set on it.
