### ISSUE TITLE
[REQ] Whitelist by flag

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#20]
In addition to the whitelist feature, it would be an interesting option to automatically release any player that has X flag on the server. For example, I would like to grant access to some requirements only to those who have the `@css/vip` flag. 

I would like to leave only the GameBan check, VAC Ban and the rest of the checks it passes if it has the `@css/vip` flag.

**Comment by K4ryuu** [comment]
You can use `@css/bypasspremiumcheck ` to bypass the checks. No other bypass going to be added.

**Comment by crashzk** [comment]
> You can use `@css/bypasspremiumcheck ` to bypass the checks. No other bypass going to be added.

I used this bypass and the player was still kicked from the server.

Test I did was, I removed the player's STEAMID from the database, he deprived his entire Steam profile, I added the VIP for him, I set the permission `@css/bypasspremiumcheck` and even so he is being expelled, VIP shows active for him .

**Comment by crashzk** [comment]
Update: Now it apparently worked, I checked the configs and bypass again, saved and restarted the server and it worked.
