### ISSUE TITLE
[REQ] Improvements to the system for saving the whitelist in the database

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#21]
During the tests I carried out, I noticed that, when a player has access granted by the `@css/bypasspremiumcheck` permission, he is added to the database, even without having the requirements or a public profile.

If the same player later has the permission removed, he still has access to the server since he was added to the whitelist. It would be interesting to ensure that players with this permission are not added to the database, as it passes all the requirements even without having them. The verification should only work for players without permissions on the servers, this way we can avoid this problem that I mentioned above.

Or even better, how it saves the information in the database, at the moment it only saves the player's SteamID and when it expires, it does not save information about their steam level, cs2, private profile or not, hours of play, etc.

**Comment by K4ryuu** [comment]
This is why you can set how long the database should store the validation responses. Please use it to re-validate your players on a specified interval...
