### ISSUE TITLE
[BUG] not working with css 142

### ISSUE THREAD

**Issue by rabi07** [KitsuneLab-Development/CS2-SteamRestrict#3]
**Describe the bug**
The plugin is loaded with proper config with a valid key

{
  "SteamWebAPI": "XXXXXXXXXXXXXXXXXXXXXX",
  "MinimumHourNonPrime": 1000,
  "MinimumHourPrime": 10,
  "MinimumLevelNonPrime": 50,
  "MinimumLevelPrime": 50,
  "BlockPrivateProfile": true,
  "BlockNonPrime": true,
  "BlockTradeBanned": false,
  "BlockGameBanned": true
}

looks like its not working. i have able to join with non-prime and private profile

**Media (Optional)**

![image](https://github.com/K4ryuu/CS2_SteamRestrict/assets/38426299/eba1667d-d574-40f6-aecb-21c9790a1982)

**Logs (Optional)**

Got one error msg in the console

[S_API FAIL] Tried to access Steam interface SteamUtils010 before SteamAPI_Init succeeded.

**Comment by criskkky** [comment]
Fix pls

**Comment by criskkky** [comment]
@K4ryuu

**Comment by K4ryuu** [comment]
Greetings,
I'm checking on it tomorrow (since today I patched only K4).
Thank you for the report!

**Comment by blady334** [comment]
@K4ryuu Has anything moved in this matter?
