### ISSUE TITLE
install CS2_SteamRestrict plugin but doesn't work

### ISSUE THREAD

**Issue by harish0067** [KitsuneLab-Development/CS2-SteamRestrict#4]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Media (Optional)**
If applicable, add screenshots or videos to help explain your problem.

**Logs (Optional)**
If applicable, add logs to help explain your problem.

**Additional context (Optional)**

**Comment by crashzk** [comment]
Duplicate #3
