### ISSUE TITLE
Please Update!!!

### ISSUE THREAD

**Issue by hunghippo** [KitsuneLab-Development/CS2-SteamRestrict#6]
cssharp: 188
metamod: 2.0dev

**Comment by K4ryuu** [comment]
Could you give me some detail why it would need an update? x)

**Comment by hunghippo** [comment]
> Could you give me some detail why it would need an update? x)

Plugin gets to loaded stage, although after configuring it does not restrict nor kick or do anything what so ever.
An example of this is I've set a minimum of 1000 prime hours which my prime account does not have and it still allows me to connect. I know for a fact that my web api key is registered and works. I even tried removing myself as an administrator which didn't yield any other results.

Either the plugin is in a non working state or I'm just dumb and not doing it right?

**Comment by K4ryuu** [comment]
While you are being added as root, you possibly have the `@css/bypasspremiumcheck` flag, which grants you a bypass. When you remove your permissions you have to restart the server in order to apply those changes.

**Comment by hunghippo** [comment]
> While you are being added as root, you possibly have the `@css/bypasspremiumcheck` flag, which grants you a bypass. When you remove your permissions you have to restart the server in order to apply those changes.

Yes I do understand although as I've said I completely removed myself as an administrator this includes root access.

I'm curious have you tested your plugin recently with up to date cssharp and metamod? I would like to determine if the issue is just on my end or if it is the plugin.

**Comment by K4ryuu** [comment]
Please pass the connect log you see when you join on the server.

**Comment by lugaamn** [comment]
Is it necessary to change the CFG to include only PRIME eligible players?

**Comment by K4ryuu** [comment]
You have to set the non-prime playtime to something like `200000` and you are good to go.
