### ISSUE TITLE
Prime restrict not working 

### ISSUE THREAD

**Issue by L3sh44** [KitsuneLab-Development/CS2-SteamRestrict#8]
Hello,I have these values in the cfg, but players without prime still have access to the server, am I doing everything right?
{
  "SteamWebAPI": "my web api",
  "MinimumCS2LevelPrime": 1,
  "MinimumCS2LevelNonPrime": -1, 
  "MinimumHourPrime": 1,
  "MinimumHourNonPrime": -1,
  "MinimumLevelPrime": 5,
  "MinimumLevelNonPrime": -1,
  "MinimumSteamAccountAgeInDays": 30,
  "BlockPrivateProfile": false,
  "BlockTradeBanned": false,
  "BlockGameBanned": false,
  "ConfigVersion": 1
}

**Comment by K4ryuu** [comment]
If you want to block NonPrime player from joining then set `MinimumHourNonPrime` for example to `200000`. Definitely no-one have that many hours in cs. x)

If you set it to -1 that means you disable that check.
