### ISSUE TITLE
[REQ] Improvements to the whitelist system

### ISSUE THREAD

**Issue by crashzk** [KitsuneLab-Development/CS2-SteamRestrict#9]
We currently have `"@css/bypasspremiumcheck"` to add the player to the whitelist and release access to all restrictions. It would be interesting to have some way of choosing which restriction the player will be immune to.

Example, I would like to add the player to the whitelist only for the **Game Ban & Trade Ban** restrictions, the rest would still be checked.

I believe a **.JSON** file to configure this whitelist would be perfect.

Can we expect something like this?

**Note:** If implemented, we could even add support for adding players to the whitelist by _STEAM_ID_, so we can release a specific player.

**Comment by K4ryuu** [comment]
Hey,
First of all sorry for the late reply.
I find this feature useless because if you want to whitelist someone, you are going to whitelist from being validated by any of the checks. I see no point to whitelist from one, if you know that the user won't pass the other checks. :/

**Comment by crashzk** [comment]
@K4ryuu I understand your argument, but in my case it would be for this use.

My servers have a limit of hours for players who do not have Prime Status, X hours for them to connect to the servers..

However, many purchase VIP on the server and would like to have access to the server, even without having the necessary hours. However, for security, I would like to only allow NomPrime access, that is, even without Prime and without the necessary hours, if you have VIP it connects.

However, if you take VAC/GameBan it is blocked in the same way, even though you have VIP and are immune to the Hours requirement for NomPrime.

**Comment by K4ryuu** [comment]
The feature has been implemented to the upcoming release.
